[book]
title = "The HEMTT Book"
description = "Everything you need to build Arma 3 mods with HEMTT"
authors = ["Brett Mayson"]
language = "en"
src = "book"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/brettmayson/HEMTT/tree/main/book"
edit-url-template = "https://github.com/brettmayson/HEMTT/edit/main/{path}"
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-js = ["book/time.js", "book/whichlang.js"]
additional-css = ["book/whichlang.css"]

[build]
build-dir = "target/book"

[preprocessor]

[preprocessor.lints]
command = "cargo run --bin hemtt-book-gen"
